weather_analytics:
  outputs:
    dev:
      dbname: weather_db
      host: db
      pass: tarzangame
      port: 5432
      schema: dev
      threads: 4
      type: postgres
      user: anirudh
  target: dev
